# Copy this to .streamlit/secrets.toml (do not commit real secrets to Git)
sheets_key = "YOUR_GOOGLE_SHEET_KEY"
# Paste the full JSON for your service account between the triple quotes
gcp_service_account_json = """
{
  "type": "service_account",
  "...": "..."
}
"""
