env = "prod"

AWS_ACCESS_KEY_ID = "your-key-here"
AWS_SECRET_ACCESS_KEY = "your-secret-here"
SPAPI_REFRESH_TOKEN = "your-refresh-token"
SPAPI_CLIENT_ID = "your-client-id"
SPAPI_CLIENT_SECRET = "your-client-secret"
SPAPI_ROLE_ARN = "your-role-arn"
REGION = "us-east-1"

# Google Sheets
gSheets_credentials = """{
  "type": "service_account",
  "project_id": "your-project",
  "private_key_id": "xxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "svc-your-bot@your-project.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc-your-bot%40your-project.iam.gserviceaccount.com"
}"""

gSheets_product_sheet_id = "..."
gSheets_ppc_sheet_id = "..."
