# .streamlit/secrets.toml (example)
env = "staging"

# Amazon SP‑API (placeholders)
sp_api_client_id = ""
sp_api_client_secret = ""
sp_api_refresh_token = ""
sp_api_role_arn = ""

# Google Sheets
gsheets_credentials = """{
  "type": "service_account",
  "project_id": "your-project",
  "private_key_id": "xxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "svc-your-bot@your-project.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc-your-bot%40your-project.iam.gserviceaccount.com"
}"""

gsheets_product_sheet_id = ""
gsheets_ppc_sheet_id = ""
