# .streamlit/secrets.toml

env = "staging"

# --- Google Sheets (optional, safe to leave empty until ready) ---
gSheets_credentials = """{
  "type": "service_account",
  "project_id": "placeholder-project",
  "private_key_id": "placeholder-key-id",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nPLACEHOLDER\\n-----END PRIVATE KEY-----\\n",
  "client_email": "placeholder-bot@placeholder.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/placeholder"
}"""

gSheets_product_sheet_id = "placeholder-sheet-id"
gSheets_ppc_sheet_id = "placeholder-sheet-id"
