# .streamlit/secrets.toml
env = "staging"

sp_api_client_id = ""
sp_api_client_secret = ""
sp_api_refresh_token = ""

gsheets_credentials = ""

gsheets_product_sheet_id = ""
gsheets_ppc_sheet_id = ""
gsheets_finance_sheet_id = ""
gsheets_compliance_sheet_id = ""
gsheets_keywords_sheet_id = ""
gsheets_competitors_sheet_id = ""
gsheets_changes_log_sheet_id = ""
